version: "3.9"

services:
  lawchat-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cs317-ck_lawchat
    ports:
      - "8000:8000"
    depends_on:
      - prometheus
      # - fluentd
    env_file:
      - .env
    volumes:
      # - ./fluentd:/fluentd 
      # - ./logs:/fluentd/log      
      - ./logs:/logs
    logging:
      driver: "json-file"    
    restart: always
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: cs317-ck_prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    container_name: cs317-ck_node-exporter
    pid: "host"
    restart: unless-stopped
    ports:
      - "9100:9100"
    networks:
      -  monitoring

  grafana:
    image: grafana/grafana
    container_name: cs317-ck_grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: always
    networks:
      - monitoring

  loki:
    image: grafana/loki:2.9.0
    container_name: cs317-ck_loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml
      - ./loki/data:/loki        
    command: -config.file=/etc/loki/local-config.yaml
    restart: always
    user: root
    networks:
      - monitoring


  promtail:
    image: grafana/promtail:2.9.0
    container_name: cs317-ck_promtail
    restart: always
    depends_on:
      - loki
    command: -config.file=/etc/promtail/promtail-config.yaml
    volumes:
      - ./logs:/logs:ro                        # <-- api.log
      - promtail_positions:/tmp                      # <-- positions.yaml
      - ./promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - /var/log:/var/log:ro                         # <-- syslog
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    user: root
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager
    container_name: cs317-ck_alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
    ports:
      - "9093:9093"
    restart: always
    networks:
      - monitoring

volumes:
  promtail_positions:
networks:
  monitoring:
    driver: bridge
