groups:
  - name: chatbot-alerts
    rules:

      # 1. Cảnh báo nếu 95% request mất hơn 25s để phản hồi
      - alert: HighRequestLatency
        expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{handler="/chat"}[5m])) by (le)) > 25
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Độ trễ cao trên endpoint /chat"
          description: "95% request tới /chat có độ trễ lớn hơn 25s."

      # 2. Cảnh báo nếu inference trung bình > 25s (dựa trên metric `chat_inference_duration_seconds`)
      - alert: SlowInference
        expr: rate(chat_inference_duration_seconds_sum[5m]) / rate(chat_inference_duration_seconds_count[5m]) > 25
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Thời gian suy luận chậm"
          description: "Trung bình thời gian inference vượt quá 25s."

      # 3. Tỉ lệ lỗi 5xx > 5% trong 1 phút
      - alert: High5xxErrorRate
        expr: sum(rate(http_requests_total{handler="/chat", status=~"5.."}[1m])) / sum(rate(http_requests_total{handler="/chat"}[1m])) > 0.05
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Tỉ lệ lỗi 5xx cao"
          description: "Hơn 5% request tới /chat trả về lỗi 5xx."

      # 5. Sử dụng RAM cao
      - alert: HighMemoryUsage
        expr: process_resident_memory_bytes > 500000000  # > ~600MB (tăng từ 300MB)
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Dùng nhiều RAM"
          description: "Tiến trình chatbot dùng quá 500MB RAM."

      # 7. Không có request nào tới API trong 5 phút
      - alert: NoAPIRequests
        expr: sum(rate(http_requests_total{handler!="/metrics"}[5m])) < 0.002 
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Không có request API"
          description: "Không có request nào gửi tới chatbot trong 5 phút qua."
