global:
  scrape_interval: 15s

rule_files:
  - "/etc/prometheus/alert.rules.yml"
  
scrape_configs:
  - job_name: 'lawchat-api'
    metrics_path: /metrics
    static_configs:
      - targets: ['lawchat-api:8000']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
